version: '0.0.0.{build}' 
image: Visual Studio 2017 
branches: 
  only: 
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true 
install: 
  # Install repo specific stuff here
  - ps: Install-Product node
  - npm install -g @angular/cli
before_build: 
  # Display .NET Core version 
  - cmd: dotnet --version 
  # Display minimal restore text 
  - cmd: dotnet restore ./src/Speedway.sln --verbosity m 
build_script: 
  # output will be in ./src/bin/debug/netcoreapp1.1/publish 
  - cmd: dotnet publish ./src/Speedway.sln 
after_build: 
  # For once the build has completed 
artifacts: 
 - path: '\src\bin\Debug\netcoreapp1.1\publish' 
   name: WebSite 
   type: WebDeployPackage 
clone_depth: 1 
test_script:
  # restore packages for our unit tests 
  #- cmd: dotnet restore ./tests/tests.csproj --verbosity m 
  # run the unit tests (requires changing into the test directory) 
  #- cmd: cd tests 
  #- cmd: dotnet xunit
  #- cd "./src/Speedway.Web/Speedway.Web.Administration/Speedway.Web.Administration.Client/speedway-web-administration-client"
  - npm install "./src/Speedway.Web/Speedway.Web.Administration/Speedway.Web.Administration.Client/speedway-web-administration-client" --save
  - npm run ng build --prefix "./src/Speedway.Web/Speedway.Web.Administration/Speedway.Web.Administration.Client/speedway-web-administration-client"
  - ng test --single-run

deploy_script:
  - npm install -g firebase-tools
  # - cd "./src/Speedway.Web/Speedway.Web.Administration/Speedway.Web.Administration.Client/speedway-web-administration-client"
  - npm install --save
  - ng build --prod
  - cd dist
  - firebase deploy --token $FIREBASE_DEPLOY_KEY

on_finish : 
  # any cleanup in here
